name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      SHARING_DATA: $GITHUB_WORKSPACE/SharingData.txt

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: echo $SHARING_DATA && cargo build --verbose
